package com.example.syncy_p2p.p2p.core

enum class Event(val eventName: String) {
    PEERS_UPDATED("PEERS_UPDATED"),
    CONNECTION_INFO_UPDATED("CONNECTION_INFO_UPDATED"),
    THIS_DEVICE_CHANGED("THIS_DEVICE_CHANGED"),
    MESSAGE_RECEIVED("MESSAGE_RECEIVED"),
    FILE_RECEIVED("FILE_RECEIVED"),
    CONNECTION_STATE_CHANGED("CONNECTION_STATE_CHANGED")
}
